#!/bin/sh

# Install depot-pm if necessary
which depot-pm 1>/dev/null 2>&1 || {
    [ -z "${PIP}" ] && {
        which pip3 1>/dev/null 2>&1 && PIP=pip3
    } || {
        which pip 1>/dev/null 2>&1 && PIP=pip || {
            easy_install pip
            PIP=pip
        }
    }
    # Go
    ${PIP} install depot-pm
}
# Run install
depot-pm install
